# Generated by Django 6.0.4 on 2026-04-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="项目名称")),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="URL标识"),
                ),
                ("description", models.TextField(verbose_name="描述")),
                ("tech_stack", models.JSONField(default=list, verbose_name="技术栈")),
                (
                    "image",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="图片标识"
                    ),
                ),
                ("github", models.URLField(blank=True, verbose_name="GitHub链接")),
                ("demo", models.URLField(blank=True, verbose_name="演示链接")),
                ("highlights", models.JSONField(default=list, verbose_name="项目亮点")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="是否发布"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
                "db_table": "skyblog_project",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
