# Generated by Django 4.2.30 on 2026-04-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="github",
            field=models.URLField(blank=True, verbose_name="GitHub 链接"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="项目封面/图片标识"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="URL 标识"),
        ),
    ]
