# Generated by Django 4.2.30 on 2026-04-22 02:44

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_github_alter_project_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_prefix",
                    models.CharField(
                        default="项目", max_length=80, verbose_name="标题前半部分"
                    ),
                ),
                (
                    "title_accent",
                    models.CharField(
                        default="作品", max_length=80, verbose_name="标题强调部分"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="这里展示的项目内容，已经改为直接读取后台已发布数据。",
                        verbose_name="页面说明",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        default=projects.models.default_project_page_filters,
                        verbose_name="筛选按钮",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "项目页配置",
                "verbose_name_plural": "项目页配置",
                "db_table": "skyblog_project_page_content",
                "ordering": ["-is_active", "-updated_at"],
            },
        ),
    ]
