# Generated by Codex on 2026-04-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="xmind_file",
            field=models.CharField(blank=True, max_length=255, verbose_name="XMind 源文件"),
        ),
    ]
