# Generated by Django 4.2.30 on 2026-04-20 07:47

import articles.models
from django.db import migrations, models


def create_default_about_profile(apps, schema_editor):
    about_profile = apps.get_model("articles", "AboutProfile")
    if about_profile.objects.exists():
        return

    about_profile.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_xmind_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Sky", max_length=80, verbose_name="名称"),
                ),
                (
                    "title",
                    models.CharField(
                        default="Python 开发者 & AI 应用实践者",
                        max_length=120,
                        verbose_name="身份标题",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        default="中国", max_length=80, verbose_name="所在地"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="hello@example.com",
                        max_length=254,
                        verbose_name="联系邮箱",
                    ),
                ),
                (
                    "github",
                    models.URLField(
                        blank=True,
                        default="https://github.com",
                        verbose_name="GitHub 链接",
                    ),
                ),
                (
                    "slogan",
                    models.CharField(
                        default="用代码记录学习，用 AI 扩展创造。",
                        max_length=200,
                        verbose_name="一句话介绍",
                    ),
                ),
                (
                    "avatar_text",
                    models.CharField(
                        default="S", max_length=10, verbose_name="头像文字"
                    ),
                ),
                (
                    "page_title",
                    models.CharField(
                        default="关于我", max_length=80, verbose_name="页面标题"
                    ),
                ),
                (
                    "page_description",
                    models.CharField(
                        default="探索我的技术旅程和成长轨迹",
                        max_length=200,
                        verbose_name="页面描述",
                    ),
                ),
                (
                    "intro_title",
                    models.CharField(
                        default="你好，我是 Sky",
                        max_length=120,
                        verbose_name="简介标题",
                    ),
                ),
                (
                    "intro_paragraphs",
                    models.JSONField(
                        default=articles.models.default_intro_paragraphs,
                        verbose_name="简介段落",
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        default=articles.models.default_about_skills,
                        verbose_name="技能栏",
                    ),
                ),
                (
                    "directions",
                    models.JSONField(
                        default=articles.models.default_directions,
                        verbose_name="发展方向",
                    ),
                ),
                (
                    "experiences",
                    models.JSONField(
                        default=articles.models.default_experiences,
                        verbose_name="项目经历",
                    ),
                ),
                (
                    "certifications",
                    models.JSONField(
                        default=articles.models.default_certifications,
                        verbose_name="证书/学习记录",
                    ),
                ),
                (
                    "tools",
                    models.JSONField(
                        default=articles.models.default_tools, verbose_name="工具与环境"
                    ),
                ),
                (
                    "abilities",
                    models.JSONField(
                        default=articles.models.default_abilities,
                        verbose_name="核心能力",
                    ),
                ),
                (
                    "contact_title",
                    models.CharField(
                        default="一起交流技术与 AI 实践",
                        max_length=120,
                        verbose_name="联系区标题",
                    ),
                ),
                (
                    "contact_description",
                    models.TextField(
                        default="如果你对 Python、Django、Vue 或 AI 应用开发感兴趣，欢迎随时联系我交流。",
                        verbose_name="联系区描述",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "关于资料",
                "verbose_name_plural": "关于资料",
                "db_table": "skyblog_about_profile",
                "ordering": ["-is_active", "-updated_at"],
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(verbose_name="正文"),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="URL 标识"),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(default="标签", max_length=10, verbose_name="图标"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=30, verbose_name="标签名称"),
        ),
        migrations.RunPython(create_default_about_profile, migrations.RunPython.noop),
    ]
